export const skillData = [
  {
    title: "Frontend",
    items: [
      "React",
      "NextJS",
      "Redux",
      "React Toolkit",
      "React Query",
      "React Router Dom",
      "JWT",
      "Auth0",
      "Bootstrap",
      "Tailwind CSS",
      "Shadcn-ui",
      "React Hook Form",
    ],
    icon: "laptop-code",
  },
  {
    title: "Backend",
    items: [
      "Node.js,",
      "Express (utilizing MVC architecture)",
      "Rest API",
      "GraphQL",
      "Object-Oriented Programming",
      "Object-Relational Mapping (OPM)",
      "Apollo",
      "SQL",
      "Sequelize",
      "MongoDB",
      "Mongoose",
      "Express Validator",
    ],
    icon: "server",
  },
  {
    title: "Testing and Development Tools",
    items: [
      "Git",
      "jest",
      "Insomnia",
      "Postman",
      "TDD",
      "Playwright",
      "Heroku",
      "Render",
      "Vercel",
    ],
    icon: "toolbox",
  },
  {
    title: "Productivity",
    items: ["Slack", "Zoom", "Microsoft Office Suits"],
    icon: "lightbulb",
  },
];
