export const skillData = [
  {
    title: "Programming Languages",
    items: ["C#", "TypeScript", "JavaScript", "SQL", "Bash", "HTML5", "CSS3"],
    icon: "terminal",
  },
  {
    title: "Backend",
    items: [
      ".NET Core / ASP.NET Core Web API",
      "Minimal APIs",
      "Entity Framework Core",
      "Dapper",
      "AutoMapper",
      "FluentValidation",
      "LINQ",
      "Node.js",
      "Express (MVC)",
      "REST APIs",
      "GraphQL",
    ],
    icon: "server",
  },
  {
    title: "Architecture",
    items: [
      "Microservices",
      "Clean Architecture",
      "Event-driven messaging",
      "OOP",
      "SOLID principles",
    ],
    icon: "microchip",
  },
  {
    title: "Frontend",
    items: [
      "React",
      "Next.js",
      "Redux Toolkit",
      "React Query",
      "Tailwind CSS",
      "Bootstrap",
    ],
    icon: "laptop-code",
  },
  {
    title: "Databases",
    items: ["SQL Server", "PostgreSQL", "MySQL", "MongoDB (Mongoose)"],
    icon: "server",
  },
  {
    title: "Testing",
    items: [
      "Test-Driven Development (TDD)",
      "xUnit",
      "Moq",
      "Jest",
      "Playwright",
    ],
    icon: "toolbox",
  },
  {
    title: "Cloud & DevOps",
    items: [
      "Azure (AKS, DevOps, API Management, Service Bus, Key Vault, Entra ID B2C)",
      "AWS",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Ansible",
      "Jenkins",
      "GitHub Actions",
      "RabbitMQ",
      "Redis",
      "Polly",
      "Ocelot",
      "CI/CD pipelines",
    ],
    icon: "microchip",
  },
  {
    title: "Tools",
    items: ["Git", "Postman", "Insomnia", "Linux", "JWT"],
    icon: "toolbox",
  },
];
